spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-edu?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  mail:
    protocol: smtp
    host: smtp.qq.com
    default-encoding: utf-8
    username: 506000502@qq.com
    password: izdwixkbmmzkbgbg
authcode:
  expiretime: 600000
ip:
  minute: 1
  maxreqnum: 8
management:
  endpoints:
    web:
      exposure:
        include: "*"
