spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: 18852676039@163.com
    password: ENKCEDSUODGKDAGF
    default-encoding: UTF-8
authcode:
  expiretime: 600000
ip:
  minute: 1
  maxreqnum: 7
management:
  endpoints:
    web:
      exposure:
        include: "*"
